# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False)),
                ('a_filename', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FriendStatus',
            fields=[
                ('f_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FriendValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('friendship_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irproject.FriendStatus')),
            ],
        ),
        migrations.CreateModel(
            name='Queries',
            fields=[
                ('q_id', models.AutoField(primary_key=True, serialize=False)),
                ('q_filename', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='QueriesReceived',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='queriesreceived',
            name='asked_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irproject.Users'),
        ),
        migrations.AddField(
            model_name='queriesreceived',
            name='question_asked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irproject.Queries'),
        ),
        migrations.AddField(
            model_name='queries',
            name='asked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irproject.Users'),
        ),
        migrations.AddField(
            model_name='friendvalue',
            name='value_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irproject.Users'),
        ),
        migrations.AddField(
            model_name='friendstatus',
            name='req_receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='irproject.Users'),
        ),
        migrations.AddField(
            model_name='friendstatus',
            name='req_sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='irproject.Users'),
        ),
        migrations.AddField(
            model_name='answers',
            name='answered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irproject.Users'),
        ),
        migrations.AddField(
            model_name='answers',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irproject.Queries'),
        ),
    ]
